# Generated by Django 3.2.3 on 2021-05-31 17:12

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sub', models.BooleanField(default=False, verbose_name='زیر مجموعه است')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='شناسه')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='core.category', verbose_name='زیر مجمموعه')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': '۱.گروه ها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'آلبوم',
                'verbose_name_plural': '۴.آلبوم ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='شناسه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('inventory', models.SmallIntegerField(verbose_name='موجودی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد محصول')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروز رسانی محصول')),
                ('code', models.IntegerField(default=core.models.random_int, editable=False, verbose_name='کد محصول')),
                ('category', models.ManyToManyField(related_name='products', to='core.Category', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': '۲.محصولات',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/', verbose_name='فایل عکس')),
                ('default', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.imagealbum', verbose_name='آلبوم عکس')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': '۳.عکس ها',
            },
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='core.product', verbose_name='محصول'),
        ),
    ]
