# Generated by Django 3.2.3 on 2021-05-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='ایمیل')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='تلفن')),
                ('is_active', models.BooleanField(default=True, verbose_name='کاربر فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربرها',
            },
        ),
    ]
